title: generic-python-turtle-moving-without-drawing
hero_image: images/banner.png
description: Moving a Python turtle without drawing
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: false
interests: "graphics"
technologies: "python, turtle"
steps:
  - title: Moving without drawing
